### ISSUE TITLE
BACKUP 

### ISSUE THREAD

**Issue by JhoelFloresS** [JhoelFloresS/Proyecto-de-SI2#11]
implementar el backup de la base de datos para los tenant, spatie/laravel-backup

**Comment by andreschilva** [comment]
tienen que agregar la ruta donde se encuentra mysqldump.exe en la variable  de entorno Path de windows para que pueda ejecutar mysqldump, por ejemplo C:\xampp\mysql\bin, luego reiniciar la compu

**Comment by andreschilva** [comment]
lo hice sin spatie/laravel-backup, pero funca xd
